//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlAlbum.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumDetail
    {
        public int idAlbum { get; set; }
        public int idSong { get; set; }
        public string song { get; set; }
        public string singer { get; set; }
        public string link { get; set; }
    
        public virtual ListAlbum ListAlbum { get; set; }
    }
}
